-- create schema used for API
create schema api;

-- create table used for log events
create table api.events (
	id serial primary key,
	event jsonb not null
);

\n-- End of sql/01_create-tables.sql --\n
-- sql/03_create-view.sql

DROP VIEW IF EXISTS api.events_view;
CREATE OR REPLACE VIEW api.events_view AS
SELECT
  *,
  -- flatten user_id: pick first array element, then scalar field, then fallback
  COALESCE(
    event->'subject'->>0,    -- dhair2-style array
    event->>'subject',       -- simple string
    event->>'user_id'        -- legacy key
  ) AS user_id,

  -- flatten event_type: use explicit action first, then event_type, then tags, then message
  COALESCE(
    event->>'action',
    event->>'event_type',
    event->'tags'->>0,
    event->>'message'
  ) AS event_type,

  -- new: pull the JSON "version" field into its own column
  event->>'version' AS version,

  -- schema_version: treat Keycloak as legacy, then LTT, then any existing schema_version, else 'legacy'
  CASE
    WHEN event->>'realmId' IS NOT NULL          THEN 'legacy'
    WHEN event->>'source_system' = 'LTT'         THEN 'ltt'
    WHEN event->>'schema_version' IS NOT NULL    THEN event->>'schema_version'
    WHEN event->>'version' IS NOT NULL           THEN event->>'version'
    ELSE 'legacy'
  END AS schema_version,

  -- coalesce all timestamp sources, normalizing commas to dots for asctime
  COALESCE(
    (event->>'event_time')::timestamptz,                                   -- ISO-8601
    (event->>'occurred')   ::timestamptz,                                   -- dhair2
    TO_TIMESTAMP(event->>'created_at', 'YYYY-MM-DD HH24:MI:SS'),           -- legacy
    REPLACE(event->>'asctime', ',', '.')::timestamptz,                     -- Python asctime
    TO_TIMESTAMP((event->>'timestamp')::bigint / 1000)                     -- Keycloak’s epoch-ms
  ) AS occurred_at

FROM api.events;
\n-- End of sql/03_create-view.sql --\n
\n-- INSERT statements for Legacy from datasets/logs.sql
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "asctime": "2021-09-08 17:23:43,275", "message": "Exception on / [GET]", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/flask_oidc/__init__.py\", line 356, in _get_cookie_id_token\n    return self.cookie_serializer.loads(id_token_cookie)\n  File \"/usr/local/lib/python3.7/site-packages/itsdangerous/jws.py\", line 143, in loads\n    self.make_signer(salt, self.algorithm).unsign(want_bytes(s)),\n  File \"/usr/local/lib/python3.7/site-packages/itsdangerous/signer.py\", line 169, in unsign\n    raise BadSignature(\"Signature %r does not match\" % sig, payload=value)\nitsdangerous.exc.BadSignature: Signature b''zd8Sa0rbgpfYUzwmliRALEYftYC6hPqGaJ4rEF3kR8Uhl56Ijr26U-G1rc70klPbglrN5M_nuF9jx7XOTOad0Q'' does not match\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/local/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1948, in full_dispatch_request\n    rv = self.preprocess_request()\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 2242, in preprocess_request\n    rv = func()\n  File \"/usr/local/lib/python3.7/site-packages/flask_oidc/__init__.py\", line 413, in _before_request\n    self.authenticate_or_redirect()\n  File \"/usr/local/lib/python3.7/site-packages/flask_oidc/__init__.py\", line 433, in authenticate_or_redirect\n    id_token = self._get_cookie_id_token()\n  File \"/usr/local/lib/python3.7/site-packages/flask_oidc/__init__.py\", line 357, in _get_cookie_id_token\n    except SignatureExpired:\nNameError: name ''SignatureExpired'' is not defined", "levelname": "ERROR"}');
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "tags": ["search"], "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:24:16,687", "message": "PDMP found match", "patient": {"subject.id": "1", "subject:Patient.birthdate": "eq1993-09-12", "subject:Patient.name.given": "Harley", "subject:Patient.name.family": "Quinn"}, "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "asctime": "2021-09-08 17:24:17,377", "message": "launch", "subject": "Patient/1", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:24:18,367", "message": "login", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "asctime": "2021-09-08 17:24:18,468", "message": "redirecting to frontend app: https://frontend.acc.dev.cosri.cirg.washington.edu/launch.html", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:24:25,789", "message": "fire request for PDMP meds on http://pdmp-internal:8008/v/r4/fhir/MedicationOrder/?{''subject:Patient.name.family'': ''Quinn'', ''subject:Patient.name.given'': ''Harley'', ''subject:Patient.birthdate'': ''eq1993-09-12'', ''DEA'': ''FAKEDEA1234''}", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:24:27,016", "message": "PDMP returned 3 MedicationRequest/Orders", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "tags": ["application", "onload"], "asctime": "2021-09-08 17:24:29,401", "message": null, "patient": "Harley Quinn", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "tags": ["logout"], "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:25:29,239", "message": "logout on request", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "tags": ["search"], "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:25:35,241", "message": "PDMP found match", "patient": {"subject.id": "1", "subject:Patient.birthdate": "eq1993-09-12", "subject:Patient.name.given": "Harley", "subject:Patient.name.family": "Quinn"}, "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "asctime": "2021-09-08 17:25:35,623", "message": "launch", "subject": "Patient/1", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:25:36,341", "message": "login", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "asctime": "2021-09-08 17:25:36,397", "message": "redirecting to frontend app: https://frontend.acc.dev.cosri.cirg.washington.edu/launch.html", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:25:39,124", "message": "fire request for PDMP meds on http://pdmp-internal:8008/v/r4/fhir/MedicationOrder/?{''subject:Patient.name.family'': ''Quinn'', ''subject:Patient.name.given'': ''Harley'', ''subject:Patient.birthdate'': ''eq1993-09-12'', ''DEA'': ''FAKEDEA1234''}", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:25:39,241", "message": "PDMP returned 3 MedicationRequest/Orders", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "tags": ["application", "onload"], "asctime": "2021-09-08 17:25:40,559", "message": null, "patient": "Harley Quinn", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "tags": ["search"], "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:36:15,665", "message": "PDMP found match", "patient": {"subject.id": "1", "subject:Patient.birthdate": "eq1993-09-12", "subject:Patient.name.given": "Harley", "subject:Patient.name.family": "Quinn"}, "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "asctime": "2021-09-08 17:36:16,222", "message": "launch", "subject": "Patient/1", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:36:16,964", "message": "login", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "asctime": "2021-09-08 17:36:17,055", "message": "redirecting to frontend app: https://frontend.acc.dev.cosri.cirg.washington.edu/launch.html", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:36:20,406", "message": "fire request for PDMP meds on http://pdmp-internal:8008/v/r4/fhir/MedicationOrder/?{''subject:Patient.name.family'': ''Quinn'', ''subject:Patient.name.given'': ''Harley'', ''subject:Patient.birthdate'': ''eq1993-09-12'', ''DEA'': ''FAKEDEA1234''}", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:36:20,538", "message": "PDMP returned 3 MedicationRequest/Orders", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "sof_wrapper", "tags": ["application", "onload"], "asctime": "2021-09-08 17:36:22,259", "message": null, "patient": "Harley Quinn", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "tags": ["logout"], "user": {"DEA": "testDEAvalue", "username": "test"}, "asctime": "2021-09-08 17:37:57,452", "message": "logout on request", "levelname": "INFO"}');
INSERT INTO api.events (event) VALUES ('{"name": "patientsearch", "tags": ["PDMP", "search"], "user": {"DEA": "FAKEDEA1234", "username": "ivanc"}, "asctime": "2021-09-08 17:50:59,715", "message": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>Invalid XML returned from PDMP</p>\n", "patient": {"subject:Patient.birthdate": "eq1999-01-01", "subject:Patient.name.given": "Invalid", "subject:Patient.name.family": "Xml"}, "levelname": "ERROR"}');
\n-- INSERT statements for LTT (direct query) from datasets/ltt-dev-logserver.sql
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"shl": "6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE", "url": "http://shl-server.inform.dev.cirg.uw.edu/api/user/ltt-test-user", "method": "GET", "shl_session": "92ad77a3-c38b-4a7b-abb6-514a6d825c7c"}}, "source": {"type": "shl-ltt-server", "observer": "https://shl-server.inform.dev.cirg.uw.edu"}, "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:41:15.426Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Load share page", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:41:16.072Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "login", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Initialized FHIR client for user ''ltt-test-user''", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:41:16.060Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"shl": "6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Loaded SHL ''6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE''", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:41:16.300Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"shl": "6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE", "url": "https://shl-creator.inform.dev.cirg.uw.edu/view#shlink:/eyJ1cmwiOiJodHRwczovL3NobC1zZXJ2ZXIuaW5mb3JtLmRldi5jaXJnLnV3LmVkdS9hcGkvc2hsLzZQWWNNUDVYcGlLcExraUVPUG5IZ1hqbXFsdEpwRnkwVkVLSTJFUXdIZUUiLCJmbGFnIjoiIiwia2V5IjoiX3pQYTJHeXhEalhlUmFzeFM3TFlmNzJRcExIR1ZPZmRnZTVXRncyT1ZXOCJ9", "action": "Load SHL ''6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE''", "method": "POST", "session_id": "", "shl_session": "92ad77a3-c38b-4a7b-abb6-514a6d825c7c"}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:41:17.725Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "email-label", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Opened email sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:42:00.178Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "text-label", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Opened text sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:42:34.762Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "qr-label", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Opened qr sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:42:41.742Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "qr-label", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Closed sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:42:44.820Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/view#shlink:/eyJ1cmwiOiJodHRwczovL3NobC1zZXJ2ZXIuaW5mb3JtLmRldi5jaXJnLnV3LmVkdS9hcGkvc2hsLzZQWWNNUDVYcGlLcExraUVPUG5IZ1hqbXFsdEpwRnkwVkVLSTJFUXdIZUUiLCJmbGFnIjoiIiwia2V5IjoiX3pQYTJHeXhEalhlUmFzeFM3TFlmNzJRcExIR1ZPZmRnZTVXRncyT1ZXOCJ9", "Button": "main-copy", "action": "Copied SHL to clipboard", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:42:50.139Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "email-label", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Opened email sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:42:58.917Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/view#shlink:/eyJ1cmwiOiJodHRwczovL3NobC1zZXJ2ZXIuaW5mb3JtLmRldi5jaXJnLnV3LmVkdS9hcGkvc2hsLzZQWWNNUDVYcGlLcExraUVPUG5IZ1hqbXFsdEpwRnkwVkVLSTJFUXdIZUUiLCJmbGFnIjoiIiwia2V5IjoiX3pQYTJHeXhEalhlUmFzeFM3TFlmNzJRcExIR1ZPZmRnZTVXRncyT1ZXOCJ9", "Button": "email-copy", "action": "Copied SHL to clipboard", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:00.626Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "text-button", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Opened text sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:02.168Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/view#shlink:/eyJ1cmwiOiJodHRwczovL3NobC1zZXJ2ZXIuaW5mb3JtLmRldi5jaXJnLnV3LmVkdS9hcGkvc2hsLzZQWWNNUDVYcGlLcExraUVPUG5IZ1hqbXFsdEpwRnkwVkVLSTJFUXdIZUUiLCJmbGFnIjoiIiwia2V5IjoiX3pQYTJHeXhEalhlUmFzeFM3TFlmNzJRcExIR1ZPZmRnZTVXRncyT1ZXOCJ9", "Button": "text-copy", "action": "Copied SHL to clipboard", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:02.883Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "update", "entity": {"detail": {"id": "qr-label", "url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Opened qr sharing instructions", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:04.253Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Open SHL reset dialogue", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:09.054Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Close SHL reset dialogue", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:13.392Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Open SHL reset dialogue", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:16.539Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "delete", "entity": {"detail": {"shl": "6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE", "url": "http://shl-server.inform.dev.cirg.uw.edu/api/shl/6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE", "action": "Deactivated shl ''6PYcMP5XpiKpLkiEOPnHgXjmqltJpFy0VEKI2EQwHeE''", "method": "DELETE", "shl_session": "92ad77a3-c38b-4a7b-abb6-514a6d825c7c"}}, "source": {"type": "shl-ltt-server", "observer": "https://shl-server.inform.dev.cirg.uw.edu"}, "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:17.811Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Close SHL reset dialogue", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:18.566Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "http://shl-server.inform.dev.cirg.uw.edu/api/user/ltt-test-user", "action": "Get shl for user ''ltt-test-user''", "method": "GET"}}, "source": {"type": "shl-ltt-server", "observer": "https://shl-server.inform.dev.cirg.uw.edu"}, "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:18.242Z", "severity": "warning"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "login", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Initialized FHIR client for user ''ltt-test-user''", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:19.011Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "read", "entity": {"detail": {"url": "https://shl-creator.inform.dev.cirg.uw.edu/share?session_state=b8cc4e50-b838-46e8-8cda-b12b2c9fbf36", "action": "Load share page", "method": "POST", "session_id": ""}}, "source": {"type": "shl-ltt", "version": "add-logging", "observer": "https://shl-creator.inform.dev.cirg.uw.edu"}, "outcome": "", "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:19.014Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "create", "entity": {"detail": {"shl": "9zGnxdIVncQccBtmz4_giwMvPqao7Ucm9srzgADWYpo", "url": "http://shl-server.inform.dev.cirg.uw.edu/api/shl", "action": "Create shl ''9zGnxdIVncQccBtmz4_giwMvPqao7Ucm9srzgADWYpo'' for user ''ltt-test-user''", "method": "POST", "shl_session": "92ad77a3-c38b-4a7b-abb6-514a6d825c7c"}}, "source": {"type": "shl-ltt-server", "observer": "https://shl-server.inform.dev.cirg.uw.edu"}, "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:19.061Z", "severity": "info"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "ltt-test-user", "type": "user", "ip_address": "172.18.0.6", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "action": "create", "entity": {"detail": {"shl": "9zGnxdIVncQccBtmz4_giwMvPqao7Ucm9srzgADWYpo", "url": "http://shl-server.inform.dev.cirg.uw.edu/api/shl/9zGnxdIVncQccBtmz4_giwMvPqao7Ucm9srzgADWYpo/file", "file": "EGFuemDVU5iGOMJsro9ERqZTuvytg59R5Th8aHRzxo4", "action": "Add file ''EGFuemDVU5iGOMJsro9ERqZTuvytg59R5Th8aHRzxo4'' to shl ''9zGnxdIVncQccBtmz4_giwMvPqao7Ucm9srzgADWYpo''", "method": "POST", "contentType": "application/smart-health-card", "shl_session": "92ad77a3-c38b-4a7b-abb6-514a6d825c7c"}}, "source": {"type": "shl-ltt-server", "observer": "https://shl-server.inform.dev.cirg.uw.edu"}, "subject": "ltt-test-user", "version": "2", "occurred": "2025-01-30T20:43:19.261Z", "severity": "info"}');
\n-- INSERT statements for Version 3.0 (from view) from datasets/ltt-dev-logserver.sql
INSERT INTO api.events (event) VALUES ('{"agent": {"who": 0, "type": "user", "ip_address": "205.210.31.184", "user_agent": "n/a"}, "level": "info", "action": "read", "entity": {"query": "", "detail": {"action": "login", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://inform.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-02-09T03:45:01Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": 0, "type": "user", "ip_address": "198.235.24.43", "user_agent": "n/a"}, "level": "info", "action": "read", "entity": {"query": "", "detail": {"action": "login", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://inform.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-02-09T09:54:35Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": 0, "type": "user", "ip_address": "205.210.31.123", "user_agent": "\"Xpanse-bot"}, "level": "info", "action": "read", "entity": {"query": "", "detail": {"action": "login", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-30T01:01:15Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": 0, "type": "user", "ip_address": "205.210.31.123", "user_agent": "\"Xpanse-bot"}, "level": "info", "action": "read", "entity": {"query": "", "detail": {"action": "login", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://inform.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-02-02T00:17:58Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": 0, "type": "user", "ip_address": "196.251.113.74", "user_agent": "n/a"}, "level": "info", "action": "read", "entity": {"query": "", "detail": {"action": "login", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://inform.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-02-15T01:20:54Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:02Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:02Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:17Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:17Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:32Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:32Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:47Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:52:47Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:02Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:02Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:17Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:17Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:31Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:32Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:33Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "606", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "logout", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:34Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": 0, "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "login", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:35Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:53:48Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:54:03Z"}');
INSERT INTO api.events (event) VALUES ('{"agent": {"who": "594", "type": "user", "ip_address": "10.102.22.151", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"}, "level": "info", "entity": {"query": "", "detail": {"action": "authCheck", "controller": "users"}}, "source": {"type": "dhair2/inform", "observer": "https://ubu.mcjustin.dev.cirg.uw.edu"}, "version": "3.0", "occurred": "2025-01-29T23:54:18Z"}');
